### ISSUE TITLE
授权建议能改为路由控制是否需要的模式

### ISSUE THREAD

**Issue by pefecter** [zgh0711/VueProjectTemplate#2]
代码试着运行了一下,很方便,而且文档真的很详细了,直接改下参数就可以用,不过还是觉得可以用路由参数来控制该页面是否需要授权这也灵活一点,或者是弄一个白名单这也,希望能考虑加入完善

**Comment by zgh0711** [comment]
你说的是微信授权？一般依赖微信的 H5 都需要授权，我这里是按照一般的情况做的，你如果有需要可以自己修改下，改起来也很方便
